version: 2.1 
jobs: 
  build: 
    docker: 
      - image: circleci/node
    steps:
      - checkout
      - setup_remote_docker
      - run: npm install 
      - run: npm test
      - run: 
          name: Save test results 
          command: | 
            mkdir -p ~/test-results
            find . -type f -regex ".*/results/*.csv" -exec cp {} ~/test-results/ \;
          when: always
      - store_test_results: 
          path: ~/test-results
      - store_artifacts: 
          path: ~/test-results
      

