version: 2.1 
jobs: 
  build: 
    docker: 
      - image: circleci/node
    steps:
      - checkout
      - setup_remote_docker
      - run: npm install 
      - run: npm start
      - run: 
          name: Save test results 
          command: | 
            mkdir -p ~/results
            find . type f -regex "*.csv"
      - store_test_results: 
          path: /results
      

