version: 2.1 
jobs: 
  build: 
    docker: 
      - image: circleci/node
    steps:
      - checkout
      - setup_remote_docker
      - run: npm install 
      - run: npm test
      - run: 
          command: | 
            mkdir -p ~/test-results
      - store_test_results: 
          path: /results
      - store_artifacts: 
          path: /results
      

